name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run Black
        run: black --check .

  test:
    runs-on: ubuntu-latest
    needs: style_check
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage pytest-cov

      - name: Run tests with coverage
        run: pytest --cov=. --cov-report=term

      - name: Save coverage data
        uses: actions/upload-artifact@v3
        with:
          name: coverage-data
          path: .coverage
          retention-days: 1

  coverage_report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download coverage data
        uses: actions/download-artifact@v3
        with:
          name: coverage-data
          path: .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage

      - name: Generate coverage report
        run: |
          coverage report
          coverage xml

      - name: Save coverage XML
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml
          retention-days: 14
