name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install black
        run: |
          python -m venv venv 
          source venv/bin/activate  
          python -m pip install --upgrade pip  
          pip install black  

      - name: Run Black
        run: |
          source venv/bin/activate  
          black --check . 

  test:
    runs-on: ubuntu-latest
    needs: style_check
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create virtual environment
        run: |
          python -m venv venv  
          source venv/bin/activate  

      - name: Install dependencies
        run: |
          source venv/bin/activate  
          python -m pip install --upgrade pip  
          pip install -r requirements.txt  

      - name: Run tests with coverage
        run: |
          source venv/bin/activate  
          pytest --cov=. --cov-report=term --cov-report=xml --cov-config=.coveragerc  

      - name: Debug: Check coverage file
        run: ls -la

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: .coverage
          retention-days: 1
          include-hidden-files: true

  
  coverage_report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download coverage data
        uses: actions/download-artifact@v3
        with:
          name: coverage-data
          path: .  # Download .coverage file

      - name: Create virtual environment
        run: |
          python -m venv venv  
          source venv/bin/activate  

      - name: Install coverage
        run: |
          source venv/bin/activate  
          python -m pip install --upgrade pip  
          pip install coverage  

      - name: Generate coverage report
        run: |
          source venv/bin/activate  
          coverage report  
          coverage xml  

      - name: Save coverage XML
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml  
          retention-days: 14  
